BASH="C:\Program Files\Git\bin"
CMD="C:\WINDOWS\system32"
POWERSHELL="C:\WINDOWS\System32\WindowsPowerShell\v1.0"
CODE="C:\Program Files\Microsoft VS Code\bin"
GIT="C:\Program Files\Git\cmd"
JAVA="C:\Users\Julio\Meu Drive (juliomendesdev@gmail.com)\dev\java\jdk-21.0.2_windows-x64_bin\jdk-21.0.2\bin"
MAVEN="C:\Users\Julio\Meu Drive (juliomendesdev@gmail.com)\dev\maven\apache-maven-3.6.3-bin\apache-maven-3.6.3\bin"
GRADLE="C:\Users\Julio\Meu Drive (juliomendesdev@gmail.com)\dev\gradle\gradle-8.6-bin\gradle-8.6\bin"
PATH=$(/bin/cygpath -p "$BASH;$CMD;$POWERSHELL;$CODE;$GIT;$JAVA;$MAVEN;$GRADLE;")